matrix:
  include:
    - language: c
      sudo: false # only for faster builds
      compiler: 
        - clang
        - gcc
      script:
        - gcc -o test hello.c // we can use gcc instead of clang too
        - ./hello 
